### PR TITLE
Make it work in plain C apps

### PR DESCRIPTION
**Pull request by xslim**
This is a basic conversion to allow LLC work in plain old C apps.
Work done:
- check if `__OBJC__` for including `Foundation`
- `fprintf` to `stdout` as basic logger if used in C or `_LCL_LOG_C_STRING` defined
- check if `lcl_config_*` files are available, and if not - add one default "Main" component
- add default log level `lcl_vError` or `lcl_vInfo` if `DEBUG`
- add some testing:
  - install testing lib with `clib install stephenmathieson/describe.h`
  - run `make`

### CODE REVIEW

**Comment by aharren** [comment]
@xslim any news on this?

**Comment by xslim** [comment]
Yep, it works)

**Comment by aharren** [comment]
will try to release the new version on the weekend

**Comment by aharren** [comment]
https://github.com/aharren/LibComponentLogging-Core/releases/tag/1.4.1

**Pull request closed without merging**
